sudo: required
services:
  - docker

before_install: #use Dockerfile.dev to run tests. production Dockerfile doesnt give access to tests just raw html/js files
  - docker build -t bbmhmmad/react-test -f ./client/Dockerfile.dev ./client #client folder is build context

script: #primary test running section. exit code other than 0 is fail to travis-ci
  - docker run bbmhmmad/react-test npm test -- --coverage #override default start command. coverage hack to exit tests

after_success: # Production Docker builds for all apps
  - docker build -t bbmhmmad/multi-client ./client #uses default of Dockerfile dont have to specify file
  - docker build -t bbmhmmad/multi-nginx ./nginx
  - docker build -t bbmhmmad/multi-server ./server
  - docker build -t bbmhmmad/multi-worker ./worker
  #Log in to Docker CLI. echo retrieves password from env variable and emits via stdin to command after pipe
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to Docker Hub
  - docker push bbmhmmad/multi-client
  - docker push bbmhmmad/multi-nginx
  - docker push bbmhmmad/multi-server
  - docker push bbmhmmad/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-812624990241 # s3 region bucket
  bucket_path: docker-multi #name of bucket that will get created with app files
  on:
    branch: master # only deploy on changes to master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY