version: '3'
services:
  postgres:
    image: 'postgres:latest' # official postgres image from Dockerhub
  redis:
    image: 'redis:latest' # official redis image from Dockerhub
  nginx:
    restart: always # nginx should always be running
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev #just name of the file not path
      context: ./server # build context path
    volumes:
      - /app/node_modules #dont use local node_modules
      - ./server:/app #everything else in app directory in container have reference to local server 
    environment:
      - REDIS_HOST=redis #can just use name of the service. docker compose takes care of networking
      - REDIS_PORT=6379 #default port (read redis docker hub image docs)
      - PGUSER=postgres # default values from Docker hub image docs
      - PGHOST=postgres #can just use name of the service.
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev #just name of the file not path
      context: ./client # build context path
    volumes:
      - /app/node_modules #dont use local node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev #just name of the file not path
      context: ./worker # build context path
    volumes:
      - /app/node_modules #dont use local node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379